# Generated by Django 5.0.1 on 2024-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('runtime', models.CharField(max_length=10)),
                ('poster', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
